### PR TITLE
Division by zero in FvwmPager when desk_h==0 or desk_w==0

### PR DESCRIPTION
**Pull request by schaecsn**
gdb -c FvwmPager.core /usr/local/lib/X11/fvwm2/2.6.9/FvwmPager
GNU gdb (GDB) 8.3
...
Reading symbols from /usr/local/lib/X11/fvwm2/2.6.9/FvwmPager...
[New process 1]
Core was generated by `FvwmPager'.
Program terminated with signal SIGFPE, Arithmetic exception.
    at x_pager.c:1938
1938        vy = Event->xbutton.y * Scr.VHeight / (desk_h * Scr.MyDisplayHeight);

(gdb) p desk_h
$1 = 0

(gdb) p  Event->xbutton.y
$31 = -1
(gdb) p Scr.VHeight
$32 = 1080
(gdb) p desk_h
$33 = 0
(gdb) p Scr.MyDisplayHeight
$34 = 1080

(gdb) p Event->xbutton.x
$38 = 33
(gdb) p Scr.VWidth
$39 = 1920
(gdb) p desk_w
$40 = 64
(gdb) p Scr.MyDisplayWidth
$41 = 1920

### CODE REVIEW

**Comment by schaecsn** [comment]
You seem to be a little bit undecided about this bug. I think this is a real issue. Let me elaborate:

The pager consist of the desk-label area and a miniature view of the desktop. I don't see much value in the miniature view and resize the pager to the size of the desk-label area. Hence desk_h is 0.

For reasons unknown to me, clicking into the desk-label area results every now and then into a call of SwitchToDeskAndPage() which divides by desk_h.

**Comment by ThomasAdam** [comment]
Hi @schaecsn 

No. I understand what's going on. I'm just trying to beat our CI, Travis, in to working...

**Comment by schaecsn** [comment]
Will it help if I raise a second pull request or do you expect to run into the same CI issue, again?

**Comment by ThomasAdam** [comment]
Hi @schaecsn 

I've bypassed this for now -- looks like a systemic problem with TravisCI.  Will look in to it.

Merged.

**Pull request merged**
