### PR TITLE
Ta/docs to md

### PR DESCRIPTION
**Pull request by ThomasFunk**
Hi Thomas,

I've converted some manpages. Also added a conversion script. Hope this is ok ...

Kindly,
Thomas

### CODE REVIEW

**Comment by ThomasFunk** [comment]
Uhm ... I saw that the pull request includes your changes in fvwm.rst which would revert them after accepting. If you cannot cherry pick only my changes, please reject it and I will fix it today afternoon.

Sorry for my misfortune :-/

**Comment by ThomasAdam** [comment]
Thanks for this.  Couple of things:

* I don't want the conversion script --- there's a few bugs in there with it anyway since the version of groff won't be portable on all systems using it.  So if you've used this *please* check the output against the original man pages to ensure it's accurate.  If I could have written a tool to do this for the man pages, I would have.  I suspect module man pages are easier than the main fvwm man page anyway given they're less likely going to contain more elaborate markup.

* I don't think I want all the module manpages in the top-level manpages/ directory---they should stay where they are in their respective modules directory.  (The point of the manpages/ directory at the top-level is for FVWM's use; if we decide to split it up into multiple files, for instance.  Module man pages don't have that problem).

* You need to update respective Makefile.am files to ensure the man pages are generated at the appropriate time.

**Comment by ThomasAdam** [comment]
I'm away on holiday at the moment, so I'm not going to be looking at this PR any time soon, so I'll let it sit here.

**Comment by ThomasFunk** [comment]
* Yes, the conversion script is not perfect but it creates start rst files with a near formating to the original files. Ok, that groff didn't create similar outputs on different systems I haven't knewn ...

My standard procedure to check accuracy is: 2 xterms - one with the original and the other with the converted. So don't fear ;-)

* Ah, no problem. Than I will create a sub folder depending on that directory the original manpage is located.

* I thought about updating Makefile.am but I don't know how to handle this line:
`man_MANS = fvwm.1`
How should I add a new file?
`man_MANS = fvwm.1 FvwmConsole.1`
or
`man_MANS = fvwm.1, FvwmConsole.1`

As there're too much inconsistences in this pull request I will close it and reinitiate it again with the wanted changes (subfolders, no convert script).

Best,
Thomas

... and enjoy your vacation ^^

**Comment by ThomasAdam** [comment]
Don't close this, just update it with your new commits.

**Comment by ThomasAdam** [comment]
OK -- don't worry about updating `Makefile.am`, I'll do that. Don't create any directories to put the man pages in, just leave them in the module directories for now.  If we want to move them later on for whatever reason, we can do.

**Comment by ThomasFunk** [comment]
>  just leave them in the module directories for now

Uhm ... I've put them directly into the manpage folder ... 

So, should I put new ones to the same directory as the original e.g 
`bin/fvwm-menu-desktop.1.in` => `bin/fvwm-menu-desktop.rst.in` ?

**Comment by ThomasAdam** [comment]
Yes,

Whichever directory has the current .1 directories is where the rst files
must live.

Thomas Adam

**Comment by ThomasAdam** [comment]
Hi @ThomasFunk,

This isn't right---for a few reasons:

* Your diff is based off your last pull-request, and as such, has references to commits which will (and should) be obsoleted by an interactive rebase.  For example, you mention removing your converter script, but if you were to rebase your commits, this should never make it into the history anyway.

* Why are you moving the module man pages into `bin.`?  Look at where modules put their current ?roff pages---`FvwmAnimate` for instance has its man page under `modules/FvwmAnimate/` -- therefore all other RST files you're producing should live there too, and hence there should be corresponding commits to remove the `.1` files since the RST generation to ?roff should obsolete them.

I appreciate what you're giving me, don't get me wrong, but I still also have to take your work, apply it to mine, and write the remaining automake changes to hook this into the build, which is quite a bit of work on top of what I already have.

**Comment by ThomasFunk** [comment]
Hi Thomas,

> Your diff is based off your last pull-request, and as such, has references to commits which will (and should) be obsoleted by an interactive rebase. For example, you mention removing your converter script, but if you were to rebase your commits, this should never make it into the history anyway.

Sorry for that ... I didn't kew that this is possible. I will try to rebase my commits in the evening and hopefully I can revert my botch ^^

> Why are you moving the module man pages into bin.?

To get the freshest manpages I compiled Fvwm and started in bin/ converting the manpages there one by one. FvwmAnimate.1 was one of them ...

> ...  and hence there should be corresponding commits to remove the .1 files since the RST generation to ?roff should obsolete them.

Ok. So I will do this evening the following:

* Rebase my useless commits
* Move the rst files to the correct places
* Delete the corresponding obsolete .1 / .1.in files

Two questions:

1. Should I rename the rst files to rst.in by default or let them original?
2. You mentioned that I shouldn't include your changes along with the pull-request. But as I forked and cloned Fvwm the changes in fvwm.rst was available already in the fetched file of ta/docs-to-md branch ... So I cannot imagine how this happens. Do you have an explanation for that?

Thanks,
Thomas

**Comment by ThomasAdam** [comment]
On 15 June 2016 at 09:56, Thomas Funk <notifications@github.com> wrote:
>
> Two questions:
>
>    1. Should I rename the rst files to rst.in by default or let them
>    original?
>
> You only need to have .in files if there is to be some pre-processing done
via automake (such as variable substitution).  If that's not the case
(i.e., the man pages you're converting doesn't have a .in file already)
then you don't need any .in files, and hence you should just have a .rst
file.


>
>    1. You mentioned that I shouldn't include your changes along with the
>    pull-request. But as I forked and cloned Fvwm the changes in fvwm.rst was
>    available already in the fetched file of ta/docs-to-md branch ... So I
>    cannot imagine how this happens. Do you have an explanation for that?
>
>
When you do an interactive rebase, just remove my commit.  I'll manage
picking this up at some point.

**Comment by ThomasFunk** [comment]
Hi Thomas,

I've reverted the bad commits but don't know how to implement rst2man in Makefile.am.

Would you please check my try in FvwmForm's Makefile.am and correct it that I can do it in the others, too (I know you wrote that you would do it but I will learn it) ?

Thanks,
Thomas

**Comment by ThomasFunk** [comment]
Hi Thomas,

I've finished the conversion. The only manpages not converted are the deprecated ones:
./modules/FvwmDebug/FvwmGtkDebug.1
./modules/FvwmDragWell/FvwmDragWell.1.in
./modules/FvwmGtk/FvwmGtk.1.in
./modules/FvwmIconBox/FvwmIconBox.1.in
./modules/FvwmSave/FvwmSave.1.in
./modules/FvwmSaveDesk/FvwmSaveDesk.1.in
./modules/FvwmTabs/FvwmTabs.1
./modules/FvwmTaskBar/FvwmTaskBar.1.in
./modules/FvwmTheme/FvwmTheme.1.in
./modules/FvwmWharf/FvwmWharf.1.in
./modules/FvwmWinList/FvwmWinList.1.in
./modules/FvwmWindowMenu/FvwmWindowMenu.1

The only one I don't know whether to convert is:
./modules/FvwmDebug/FvwmOldDebug.1

Kindly,
Thomas

**Comment by ThomasAdam** [comment]
Thomas,

Thanks for your efforts.  However, I have hit a serious snag with `rst`, and as such have decided that in order to proceed over this hurdle, I'm switching to `asciidoc` but using `asciidoctor` instead as the renderer.  This is actually faster than `a2x`.

I'm already well over the problem I was having, and asciidoc is proving to be a lot easier than first thought.  To that end, I have pushed those changes to the same branch you've been basing your work from.

If you still want to convert the module man pages over, I'd appreciate that, and it shouldn't be too difficult.

As for the outstanding man pages you previously identified as needing conversion, do note that most of those are depecated; see what's available under `fvwm/modules/`.

I'll close this PR for now.  Sorry about that.

**Pull request closed without merging**
